<?php 
$theme_options = array (
		array(	"name" => __("General display",TEMPLATE_DOMAIN) ,
				"id" => "general_settings",
				"elements" => array(
									array(	"name" => __("Buy button label",TEMPLATE_DOMAIN) ,
											"desc" => __("This button label is used for all Buy buttons. The price is displayed after your label (eg 'Buy Now', would produce 'Buy Now $2.50'.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_buy_label",
											"std" => 'Buy Now',
											"type" => "text"),
									array(	"name" => __("Hide product/download shadow",TEMPLATE_DOMAIN) ,
											"desc" => __("Toggle the background/dropshadow for all product and download images.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_hide_product_shadow",
											"type" => "checkbox"),
									array(  "name" => __("Downloads page display mode",TEMPLATE_DOMAIN) ,
											"desc" => __("Choose which downloads to display on the downloads page",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_downloads_page_mode",
											"std" => "all",
											"options" => array( 
															array(
																"value"=>"all",
																"desc" =>__("All",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"featured",
																"desc" =>__("Featured (sticky)",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
									array(  "name" => __("Download request mode",TEMPLATE_DOMAIN) ,
											"desc" => __("Select which download request mode to use",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_download_request_mode",
											"std" => "optional",
											"options" => array( 
															array(
																"value"=>"optional",
																"desc" =>__("Optional mailing list signup",TEMPLATE_DOMAIN) ),
																array(
																"value"=>"none",
																"desc" =>__("No mailing list form",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
									array(	"name" => __("Hide empty sidebars message",TEMPLATE_DOMAIN) ,
											"desc" => __("Toggle the message that shows in empty sidebars. This message only shows to admin users and it provides a link to the widgets area",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_hide_widget_blank_message",
											"type" => "checkbox"),
											array(  "name" => __("Home bottom sidebar columns",TEMPLATE_DOMAIN) ,
											"desc" => __("Select the number of columns fr the home bottom sidebar",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_home_bottom_columns",
											"std" => "1",
											"options" => array( 
															array(
																"value"=>"1",
																"desc" =>__("One column (full width)",TEMPLATE_DOMAIN) ),
																array(
																"value"=>"2",
																"desc" =>__("Two columns",TEMPLATE_DOMAIN) ),
																array(
																"value"=>"3",
																"desc" =>__("Three columns",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
											
									array(	"name" => __("Hide Theme credit",TEMPLATE_DOMAIN) ,
											"desc" => __("Toggle the credit for this theme. If checked this credit is not shown in the footer of your site.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_theme_credit",
											"type" => "checkbox")
								)
				),
		array(	"name" => __("Mail and Analytics",TEMPLATE_DOMAIN) ,
				"id" => "mail_settings",
				"elements" => array(
									array(	"name" => __("Mail name",TEMPLATE_DOMAIN) ,
											"desc" => __("This name is used for all emails that are sent to users.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_mail_name",
											"std" => get_option('blogname'),
											"type" => "text"),
									array("name" => __("Mail address",TEMPLATE_DOMAIN) ,
											"desc" => __("This email address is used as the reply to address in any emails that are sent to customers.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_mail_address",
											"std" => get_option('admin_email'),
											"type" => "text"),
									array(	"name" => __("Google Analytics Key",TEMPLATE_DOMAIN) ,
											"desc" => __("Sign up for a google analytics account to receive a key formatted like UA-########-#",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_ga_key",
											"std" => '',
											"type" => "text"),
								)
				),
		array(	"name" => __("PayPal and Currency",TEMPLATE_DOMAIN) ,
				"desc" => __("This theme is set up to work with the payment gateway, Paypal Digital Goods for Express Checkout.",TEMPLATE_DOMAIN) ,
				"id" => "paypal_settings",
				"elements" => array(
									array(  "name" => __("Currency Settings",TEMPLATE_DOMAIN) ,
											"desc" =>__("Choose the currency you want to use and customise how your prices are displayed. Select a currency symbol, the currency symbol positon and what separator to use (e.g. $2,000.50 or 2.000,50&#8364; )",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Select a currency",TEMPLATE_DOMAIN) ,
											"desc" => __("Select the currency to use for your store.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_currency",
											"std" => "USD",
											"options" => array( 
															array(
																"value"=>"AUD",
																"desc" =>__("Australian Dollar",TEMPLATE_DOMAIN) ),
															array(
																"desc" =>__("Canadian Dollar",TEMPLATE_DOMAIN) ,
																"value"=>"CAD"),
															array(
																"desc" =>__("Czech Koruna",TEMPLATE_DOMAIN) ,
																"value"=>"CZK"),
															array(
																"desc" =>__("Danish Krone",TEMPLATE_DOMAIN) ,
																"value"=>"DKK"),
															array(
																"desc" =>__("Euro",TEMPLATE_DOMAIN) ,
																"value"=>"EUR"),
															array(
																"desc" =>__("Hong Kong Dollar",TEMPLATE_DOMAIN) ,
																"value"=>"HKD"),
															array(
																"desc" =>__("Hungarian Forint",TEMPLATE_DOMAIN) ,
																"value"=>"HUF"),
															array(
																"desc" =>__("Japanese Yen",TEMPLATE_DOMAIN) ,
																"value"=>"JPY"),
															array(
																"desc" =>__("Norwegian Krone",TEMPLATE_DOMAIN) ,
																"value"=>"NOK"),
															array(
																"desc" =>__("New Zealand Dollar",TEMPLATE_DOMAIN) ,
																"value"=>"NZD"),
															array(
																"desc" =>__("Polish Zloty",TEMPLATE_DOMAIN) ,
																"value"=>"PLN"),
															array(
																"desc" =>__("Pound Sterling",TEMPLATE_DOMAIN) ,
																"value"=>"GBP"),
															array(
																"desc" =>__("Singapore Dollar",TEMPLATE_DOMAIN) ,
																"value"=>"SGD"),
															array(
																"desc" =>__("Swedish Krona",TEMPLATE_DOMAIN) ,
																"value"=>"SEK"),
															array(
																"desc" =>__("Swiss Franc",TEMPLATE_DOMAIN) ,
																"value"=>"CHF"),
															array(
																"desc" =>__("U.S. Dollar",TEMPLATE_DOMAIN) ,
																"value"=>"USD")
														),
											"type" => "select"),
									array(	"name" => __("Currency Symbol",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_currency_symbol",
											"std" => "$",
											"type" => "text"),
									array(  "name" => __("Currency Symbol position",TEMPLATE_DOMAIN) ,
											"desc" => __("Select whether your currency symbol is shown before or after the amount (e.g $2.50 or 2.50$).",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_currency_symbol_position",
											"std" => "before",
											"options" => array( 
															array(
																"value"=>"before",
																"desc" =>__("Before",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"after",
																"desc" =>__("After",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
									array(  "name" => __("Thousands separator",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_thousand_separator",
											"std" => ",",
											"type" => "text"),
									array(  "name" => __("Decimal separator",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_decimal_separator",
											"std" => ".",
											"type" => "text"),
									array(	"name" => __(" Paypal API Settings",TEMPLATE_DOMAIN) ,
											"desc" => __("This theme integrates with PayPal via API Servers for API Signature Security. For more info see the documentation.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
												array(  "name" => __("PayPal Locale",TEMPLATE_DOMAIN) ,
											"desc" => __("Select the locale for PayPal. This will determine what PayPal screens display. Default is US.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_locale",
											"std" => "US",
											"options" => array( 
															array(
																"value"=>"AU",
																"desc" =>__("Australia",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"AT",
																"desc" =>__("Austria",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"BE",
																"desc" =>__("Belgium",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"BR",
																"desc" =>__("Brazil",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"CA",
																"desc" =>__("Canada",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"CH",
																"desc" =>__("Switzerland",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"CN",
																"desc" =>__("China",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"DE",
																"desc" =>__("Germany",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"ES",
																"desc" =>__("Spain",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"GB",
																"desc" =>__("United Kingdom",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"FR",
																"desc" =>__("France",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"IT",
																"desc" =>__("Italy",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"NL",
																"desc" =>__("Netherlands",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"PL",
																"desc" =>__("Poland",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"PT",
																"desc" =>__("Portugal",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"RU",
																"desc" =>__("Russia",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"US",
																"desc" =>__("United States",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"da_DK",
																"desc" =>__("Danish (for Denmark only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"he_IL",
																"desc" =>__("Hebrew (all)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"id_ID",
																"desc" =>__("Indonesian (for Indonesia only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"jp_JP",
																"desc" =>__("Japanese (for Japan only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"no_NO",
																"desc" =>__("Norwegian (for Norway only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"pt_BR",
																"desc" =>__("Brazilian Portuguese (for Portugal and Brazil only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"ru_RU",
																"desc" =>__("Russian (for Lithuania, Latvia, and Ukraine only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"sv_SE",
																"desc" =>__("Swedish (for Sweden only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"th_TH",
																"desc" =>__("Thai (for Thailand only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"tr_TR",
																"desc" =>__("Turkish (for Turkey only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"zh_CN",
																"desc" =>__("Simplified Chinese (for China only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"zh_HK",
																"desc" =>__("Traditional Chinese (for Hong Kong only)",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"zh_TW",
																"desc" =>__("Traditional Chinese (for Taiwan only)",TEMPLATE_DOMAIN) )			),
											"type" => "select"),
									array(  "name" => __("PayPal Express Checkout Mode",TEMPLATE_DOMAIN) ,
											"desc" => __("Select whether to use the PayPal In Context (popup window) or Standard (separate page) checkout mode.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_checkout_mode",
											"std" => "standard",
											"options" => array( 
															array(
																"value"=>"incontext",
																"desc" =>__("In Context",TEMPLATE_DOMAIN) ),
															array(
																"value"=>"standard",
																"desc" =>__("Standard",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
									array(  "name" => __("PayPal URL",TEMPLATE_DOMAIN) ,
											"desc" => __("Select whether to use the PayPal Sandbox or Production URL. You can edit the API credentials and the actual PayPal API URLs below.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_active_url",
											"std" => THEMEPREFIX."_pp_sandbox_url",
											"options" => array( 
															array(
																"value"=>THEMEPREFIX."_pp_production_url",
																"desc" =>__("Production",TEMPLATE_DOMAIN) ),
															array(
																"value"=>THEMEPREFIX."_pp_sandbox_url",
																"desc" =>__("Sandbox",TEMPLATE_DOMAIN) )
														),
											"type" => "select"),
									array(	"name" => __(" Paypal Production credentials",TEMPLATE_DOMAIN) ,
											"desc" => __("These are the credentials that you use with your live site. Be very carful when copying these - if you leave off a character or accidentally copy in a space then they won't work.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(	"name" => __("PayPal Production API username",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_production_api_username",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("PayPal Production API password",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_production_api_password",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("PayPal Production API signature",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_production_api_signature",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("PayPal Production URL",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_production_url",
											"std" => "https://api-3t.paypal.com/nvp",
											"type" => "text"),
									array(	"name" => __(" Paypal Sandbox credentials",TEMPLATE_DOMAIN) ,
											"desc" => __("These are the credentials that you use with your PayPal Sandbox account. You can obtain these by creating an account at https://developer.paypal.com.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(	"name" => __("PayPal Sandbox API username",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_sandbox_api_username",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("PayPal Sandbox API password",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_sandbox_api_password",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("PayPal Sandbox API signature",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_sandbox_api_signature",
											"std" => "",
											"type" => "text"),									
									array(  "name" => __("PayPal Sandbox URL",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_pp_sandbox_url",
											"std" => "https://api-3t.sandbox.paypal.com/nvp",
											"type" => "text")
								)
				),
		array(	"name" => __("File delivery",TEMPLATE_DOMAIN) ,
				"id" => "file_delivery_settings",
				"elements" => array(
									array(  "name" => __("File storage folder (e.g /server/folder/ )",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_file_storage",
											"std" => "",
											"type" => "text",
											"desc" => __("Your folder path must end with a slash ( / ). The file storage folder is where you put your product and download files. This folder needs to be secure and preferably below the web root (See documentation for more details).",TEMPLATE_DOMAIN) ),
									array(	"name" => __("Additional Product/Download Security",TEMPLATE_DOMAIN) ,
											"desc" => __("This Theme integrates with some third party plugins in order to provide extra security. To use these plugins with this Theme you must install and activate them and then turn on the options below.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
										array(  "name" => __("Use Download protect plugin",TEMPLATE_DOMAIN) ,
											"desc" => __("Download Protect is a third party plug-in (See documentation for details) If installed and enabled this Theme will encrypt your Product and Download links.",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_use_dlprotect",
											"std" => "",
											"type" => "checkbox"),
									array(  "name" => __("Use PDF Stamper plugin",TEMPLATE_DOMAIN) ,
											"desc" => __("PDF Stamper is a third party plug-in (See documentation for details). If installed and enabled this Theme will stamp licence information on your Product and Download PDF files",TEMPLATE_DOMAIN) ,
											"id" => THEMEPREFIX."_use_pdf_stamper",
											"std" => "",
											"type" => "checkbox")
								)
				),
		array(	"name" => __("Color and fonts",TEMPLATE_DOMAIN),
"desc" => sprintf(_x("Set the %s colors and fonts.","Var is theme name",TEMPLATE_DOMAIN),THEMENAME),
				"id" => "color_settings",
				"reset" => __("Reset to defaults",TEMPLATE_DOMAIN) 	,
							"elements" => array(
									array(  "name" => __("Use custom styles",TEMPLATE_DOMAIN),
											"desc" => __("Select whether to use custom stylesheet or the theme default.",TEMPLATE_DOMAIN),
											"id" => THEMEPREFIX."_color_styles",
											"std" => THEMEPREFIX."_default_styles",
											"options" => array( 
															array(
																"value"=>THEMEPREFIX."_default_styles",
																"desc" =>__("Default color styles",TEMPLATE_DOMAIN) 
																),
															array(
																"value"=>THEMEPREFIX."_custom_styles",
																"desc" =>__("Custom color styles",TEMPLATE_DOMAIN) 
																)
														),
											"type" => "select"),
									array(  "name" => __("Custom color styles",TEMPLATE_DOMAIN) ,
											"desc" =>__("To modify the colors of this theme:<br/><strong>Firstly</strong>, select 'Custom color styles' from the Use custom styles option above.<br/><strong>Secondly</strong>, modify these colors below.</li></ol>",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(	"name" => sprintf(_x("%s color families","Var is theme name",TEMPLATE_DOMAIN),THEMENAME),
											"desc" => __("Color families require a base color which is used to also generate tints and shades.",TEMPLATE_DOMAIN),
											"type" => "title"),
									array(  "name" => __("Call to action color Family",TEMPLATE_DOMAIN) ,
											"id" => "mb_buy_color",
											"std" => "#0ce",
											"type" => "color_tints"),
									array(  "name" => __("Information color family",TEMPLATE_DOMAIN) ,
											"id" => "mb_info_color",
											"std" => "#aaa",
											"type" => "color_tints"),
									array(  "name" => __("Form action color family",TEMPLATE_DOMAIN) ,
											"id" => "mb_action_color",
											"std" => "#39c",
											"type" => "color_tints"),
									array(  "name" => __("Secondary action color family",TEMPLATE_DOMAIN) ,
											"id" => "mb_sub_action_color",
											"std" => "#036",
											"type" => "color_tints"), 
									array(	"name" => sprintf(_x("%s specific colors","Var is theme name", TEMPLATE_DOMAIN),THEMENAME),
											"desc" => __("Specific colors are used for only one type of element.",TEMPLATE_DOMAIN),
											"type" => "title"),
									array(  "name" => __("Body background",TEMPLATE_DOMAIN),
											"id" => "mb_body_bg",
											"std" => "#444439",
											"type" => "specific_color"),
										array(  "name" => __("Background image (tiled)",TEMPLATE_DOMAIN),
											"desc" => __("The background image path needs to be relative to this theme folder or an absolute url.",TEMPLATE_DOMAIN),"id" => "mb_body_bg_image",
											"std" => "",
											"type" => "text"),
									array(  "name" => __("Content background",TEMPLATE_DOMAIN),
											"id" => "mb_content_bg",
											"std" => "#fff",
											"type" => "specific_color"),
									array(  "name" => __("Element shadow",TEMPLATE_DOMAIN),
											"id" => "mb_shadow",
											"std" => "#000",
											"type" => "specific_color"),
									array(  "name" => __("Header line color",TEMPLATE_DOMAIN) ,
											"id" => "mb_header_line",
											"std" => "#000",
											"type" => "specific_color"),
									array(  "name" => __("Link color",TEMPLATE_DOMAIN),
											"id" => "mb_linkCol",
											"std" => "#369",
											"type" => "specific_color"),
									array(  "name" => __("Link hover color",TEMPLATE_DOMAIN) ,
											"id" => "mb_linkColHover",
											"std" => "#963",
											"type" => "specific_color"),
									array(  "name" => __("Link active color",TEMPLATE_DOMAIN) ,
											"id" => "mb_linkColActive",
											"std" => "#933",
											"type" => "specific_color"),
									array(  "name" => __("Link visited color",TEMPLATE_DOMAIN),
											"id" => "mb_linkColVisited",
											"std" => "#567",
											"type" => "specific_color"),
									array(  "name" => __("Heading color",TEMPLATE_DOMAIN),
											"id" => "mb_headingCol",
											"std" => "#000",
											"type" => "specific_color"),
									array(  "name" => __("Sub heading color",TEMPLATE_DOMAIN) ,
											"id" => "mb_subHeadCol",
											"std" => "#666",
											"type" => "specific_color"),
									array(  "name" => __("Emphasis color",TEMPLATE_DOMAIN) ,
											"id" => "mb_emCol",
											"std" => "#888",
											"type" => "specific_color"),
									array(  "name" => __("Body text color",TEMPLATE_DOMAIN) ,
											"id" => "mb_bodyCol",
											"std" => "#222",
											"type" => "specific_color"),
									array(	"name" => __("Font family for large headings (h1, h2)",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Font name",TEMPLATE_DOMAIN) ,
											"id" => "mb_heading_text",
											"std" => "Bitter",
											"type" => "text"),
									array(  "name" => __("Is this a Google web font?",TEMPLATE_DOMAIN) ,
											
											"id" => "mb_heading_text_webfont",
											"std"=>"1",
											"options" => array( 
															array(
																"value"=>"0",
																"desc" =>__("Standard font",TEMPLATE_DOMAIN) 
																),
															array(
																"value"=>"1",
																"desc" =>__("Google web font",TEMPLATE_DOMAIN) 
																)
														),
											"type" => "select"),
									array(	"name" => __("Font family for all other text",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Font name",TEMPLATE_DOMAIN) ,
											"id" => "mb_body_text",
											"std" => "Arial",
											"type" => "text"),
									array(  "name" => __("Is this a Google web font?",TEMPLATE_DOMAIN) ,
											"id" => "mb_body_text_webfont",
											"std" => "0",
											"options" => array( 
															array(
																"value"=>"0",
																"desc" =>__("Standard font",TEMPLATE_DOMAIN) 
																),
															array(
																"value"=>"1",
																"desc" =>__("Google web font",TEMPLATE_DOMAIN) 
																)
														),
											"type" => "select")
								)
			),
		array(	"name" => __("Logo and navigation",TEMPLATE_DOMAIN) ,
				"desc" => __("Set the header elements. Choose the logo, and set the main navigation and logo dimensions. Use different logo's and positions for different device widths.",TEMPLATE_DOMAIN) ,
				"id" => "header_settings",
				"reset" => "Reset to defaults",
				"elements" => array(
									array(	"name" => __("Logo and navigation (large)",TEMPLATE_DOMAIN) ,
											"desc" => __("The large logo and navigation position settings are used for devices that have a width of at least 992px.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Path to logo (large)",TEMPLATE_DOMAIN) ,
											"desc" => __("Relative to the theme folder or absolute URL.",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_big",
											"std" => "images/logo.png",
											"type" => "text"),	
									array(  "name" => __("Width of logo (large)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_big_width",
											"std" => "300px",
											"type" => "text"),	
									array(  "name" => __("Height logo (large)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_big_height",
											"std" => "94px",
											"type" => "text"),
									array(  "name" => __("Nav top position (large)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navpos_large",
											"std" => "72px",
											"type" => "text"),	
									array(  "name" => __("Nav item space (large)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navitem_space_large",
											"std" => "2em",
											"type" => "text"),
									array(	"name" => __("Logo and navigation (medium)",TEMPLATE_DOMAIN) ,
											"desc" => __("The medium logo and navigation position settings are used for devices that have a width of between 768px and 992px.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Logo file (medium)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_medium",
											"std" => "images/logo_small.png",
											"type" => "text"),	
									array(  "name" => __("Width of logo (medium)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_medium_width",
											"std" => "205px",
											"type" => "text"),	
									array(  "name" => __("Height logo (medium)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_medium_height",
											"std" => "60px",
											"type" => "text"),
									array(  "name" => __("Nav top position (medium)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navpos_medium",
											"std" => "55px",
											"type" => "text"),	
									array(  "name" => __("Nav item space (medium)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navitem_space_medium",
											"std" => "1.3em",
											"type" => "text"),
									array(	"name" => __("Logo and navigation (small)",TEMPLATE_DOMAIN) ,
											"desc" => __("The small logo and navigation position settings are used for devices that have a width of less than 768px.",TEMPLATE_DOMAIN) ,
											"type" => "title"),
									array(  "name" => __("Logo file (small)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_small",
											"std" => "images/logo_small.png",
											"type" => "text"),	
									array(  "name" => __("Width of logo (small)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_small_width",
											"std" => "200px",
											"type" => "text"),	
									array(  "name" => __("Height logo (small)",TEMPLATE_DOMAIN) ,
											"id" => "mb_logo_small_height",
											"std" => "80px",
											"type" => "text"),
									array(  "name" => __("Nav top position (small)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navpos_small",
											"std" => "80px",
											"type" => "text"),	
									array(  "name" => __("Nav item space (small)",TEMPLATE_DOMAIN) ,
											"id" => "mb_navitem_space_small",
											"std" => "1em",
											"type" => "text")
								)
				),
		array(	"name" => __("Install demo content",TEMPLATE_DOMAIN) ,
				"desc" => __("Install our demo content package. This sets up all the content as per our demo site at Themeforest.net including; sample posts, products, downloads, product categories, menus and widgets.<br />You can only do this once, and this action cannot be undone, so think about it before you proceed.",TEMPLATE_DOMAIN) ,
				"id" => "install-demo",
				"submit" => __("Install demo content (no undo!)",TEMPLATE_DOMAIN) ,
				"submit_class" => "button-primary button-alert",
				"success_name" => __("Demo content installed",TEMPLATE_DOMAIN),
				"success_desc" => sprintf(_x('Congratulations, you have successfully installed the demo  content for this Theme. Why not %1$ssee how it looks%2$s?','Var 1 and 2 are the opening and closing tags for a link to the site home.',TEMPLATE_DOMAIN),'<a href="'.site_url().'" >','</a>'),
				"hide_option"=>"mbudm_demo_content",
				"hide_name" => __("Demo content installed",TEMPLATE_DOMAIN),
				"hide_desc"=>__("You have already installed the demo content for this Theme, you can't add it again because duplicate content will confuse Wordpress. If you really need to start over with your site, then a fresh install of Wordpress is advisable.",TEMPLATE_DOMAIN) )
	);
	
?>
